
// Next scene is 24
randomize();
attacking = 0;
action1slot = "Undefined";
wepcount = 0;
numshuffle = 0;
timeleft= 0;
timley = 0;
hitsleft = 0;
hitcount = 0;
hitcheck = 0;
damage = 0;
enemymaxhealth = 64;
enemyhealth = 64;
enemydef = 3;
enemyatk = 3;
enemyexp = 300;
scene = 0;
itemfind = 1;
dropchance = 0;
itemtype = 0;
itematk = 0;
itemdef = 0;
itemweaponhits = 0;
itemweapontime = 0;
itemhp = 0;
adjustment = 0;
expfinal = 0;
enemylevel = 1;
enemyname= "Cabe messed up setting this enemy name, how cringe.";
enemytype = 0;
enemydamage = 0;
enemyhit = 0;
enemyacc = 0;
enemypower = 10;
goldgain = 0;
defeatloss = 0;
unlockcrypt = false;
unlockmountain = false;
unlockvolcano = false;
unlockhell = false;
enemysuccess = "";
enemyfail = "";
vampgame = "";
increase = 0;
one=0;
two=0;
three=0;
four=0;
five=0;
six=0;
seven=0;
eight=0;
nine=0;
tens =0;
eleven = 0;
twelve = 0;
rollover = false;
potcount = 0;
gemder = 0;
goldcost = 0;
disweaponatk = "";
disweapontime = "";
disweaponhits = "";
disitematk = ""
disitemtime = "";
disitemhits = "";
itemtotal = "";
scr_init_sprite_array();
scr_doubleup();
//scr_init_object_array();

#macro gamesave 1