/// @description Insert description here
// You can write your code in this editor
if (action1.scene = 22){
ini_open("vampgame.ini")
ini_write_real("save2", "health", health);
ini_write_real("save2", "expneeded", obj_display.expneeded);
ini_write_real("save2", "counter1amt", counter_atkmult.amount);
ini_write_real("save2", "counter1cost", counter_atkmult.cost);
ini_write_real("save2", "counter1value", counter_atkmult.buffvalue);
ini_write_real("save2", "counter2amt", counter_baseatk.amount);
ini_write_real("save2", "counter2cost", counter_baseatk.cost);
ini_write_real("save2", "counter2value", counter_baseatk.buffvalue);
ini_write_real("save2", "counter3amt", counter_basedef.amount);
ini_write_real("save2", "counter3cost", counter_baseatk.cost);
ini_write_real("save2", "counter3value", counter_basedef.buffvalue);
ini_write_real("save2", "counter4amt", counter_basehealth.amount);
ini_write_real("save2", "counter4cost", counter_basehealth.cost);
ini_write_real("save2", "counter4value", counter_basehealth.buffvalue);
ini_write_real("save2", "counter5amt", counter_defmult.amount);
ini_write_real("save2", "counter5cost", counter_defmult.cost);
ini_write_real("save2", "counter5value", counter_defmult.buffvalue);
ini_write_real("save2", "counter6amt", counter_healthmult.amount);
ini_write_real("save2", "counter6cost", counter_healthmult.cost);
ini_write_real("save2", "counter6value", counter_healthmult.buffvalue);
ini_write_real("save2", "counter7amt", counter_evade.amount);
ini_write_real("save2", "counter7cost", counter_evade.cost);
ini_write_real("save2", "counter7value", counter_evade.buffvalue);
ini_write_real("save2", "counter8amt", counter_exp.amount);
ini_write_real("save2", "counter8cost", counter_exp.cost);
ini_write_real("save2", "counter8value", counter_exp.buffvalue);
ini_write_real("save2", "bust", maintext.bust);
ini_write_real("save2", "level", maintext.level);
ini_write_real("save2", "basehealth", maintext.basehealth);
ini_write_real("save2", "wepattack", maintext.weaponattack);
ini_write_real("save2", "baseatk", maintext.baseatk);
ini_write_real("save2", "basedef", maintext.basedef);
ini_write_real("save2", "weaponhits", maintext.weaponhits);
ini_write_real("save2", "weapontime", maintext.weapontime);
ini_write_real("save2", "playerexp", maintext.playerexp);
ini_write_real("save2", "headdef", maintext.headdef);
ini_write_real("save2", "headhp", maintext.headhp);
ini_write_real("save2", "chestdef", maintext.chestdef);
ini_write_real("save2", "chesthp", maintext.chesthp);
ini_write_real("save2", "glovesdef", maintext.glovesdef);
ini_write_real("save2", "gloveshp", maintext.gloveshp);
ini_write_real("save2", "legsdef", maintext.legsdef);
ini_write_real("save2", "legshp", maintext.legshp);
ini_write_real("save2", "vampexp", maintext.vampexp);
ini_write_real("save2", "totalexp", maintext.totalexp);
ini_write_real("save2", "vamptotalexp", maintext.vamptotalexp);
ini_write_real("save2", "totalprestige", maintext.totalprestige);
ini_write_real("save2", "prestigepoints", obj_prestige.prestigepoints);
ini_write_real("save2", "maxhealth", maintext.maxhealth);
ini_write_real("save2", "atk", maintext.atk);
ini_write_real("save2", "def", maintext.def);
ini_write_real("save2", "gold", maintext.gold);
ini_write_real("save2", "scrying", maintext.scrying);
ini_write_real("save2", "rez", action1.potcount);
ini_write_real("save2", "flat", action2.potcount);
ini_write_real("save2", "percent", action3.potcount);
ini_write_real("save2", "miracle", action4.potcount);
ini_write_real("save2", "dmg", action5.potcount);
ini_write_real("save2", "fury", action6.potcount);
ini_write_real("save2", "iron", action7.potcount);
ini_write_real("save2", "counter11amt", counter_potCOUNT.amount);
ini_write_real("save2", "counter11cost", counter_potCOUNT.cost);
ini_write_real("save2", "counter11value", counter_potCOUNT.buffvalue);
ini_write_real("save2", "counter21amt", counter_potDMG.amount);
ini_write_real("save2", "counter21cost", counter_potDMG.cost);
ini_write_real("save2", "counter21value", counter_potDMG.buffvalue);
ini_write_real("save2", "counter31amt", counter_potFLAT.amount);
ini_write_real("save2", "counter31cost", counter_potFLAT.cost);
ini_write_real("save2", "counter31value", counter_potFLAT.buffvalue);
ini_write_real("save2", "counter41amt", counter_potFURY.amount);
ini_write_real("save2", "counter41cost", counter_potFURY.cost);
ini_write_real("save2", "counter41value", counter_potFURY.buffvalue);
ini_write_real("save2", "counter51amt", counter_potIRON.amount);
ini_write_real("save2", "counter51cost", counter_potIRON.cost);
ini_write_real("save2", "counter51value", counter_potIRON.buffvalue);
ini_write_real("save2", "counter61amt", counter_potMIRACLE.amount);
ini_write_real("save2", "counter61cost", counter_potMIRACLE.cost);
ini_write_real("save2", "counter61value", counter_potMIRACLE.buffvalue);
ini_write_real("save2", "counter71amt", counter_potPERCENT.amount);
ini_write_real("save2", "counter71cost", counter_potPERCENT.cost);
ini_write_real("save2", "counter71value", counter_potPERCENT.buffvalue);
ini_write_real("save2", "counter81amt", counter_potTURNSKIP.amount);
ini_write_real("save2", "counter81cost", counter_potTURNSKIP.cost);
ini_write_real("save2", "counter81value", counter_potTURNSKIP.buffvalue);
ini_write_real("save2", "selvamet", maintext.metselvata);
ini_write_real("save2", "unlock1", action1.unlockcrypt);
ini_write_real("save2", "unlock2", action1.unlockmountain);
ini_write_real("save2", "unlock3", action1.unlockvolcano);
ini_write_real("save2", "unlock4", action1.unlockhell);
ini_write_real("save2", "top", maintext.toptorn)
ini_write_real("save2", "push", maintext.selvatapush)
ini_write_real("save2", "big", maintext.selvatabig)
ini_write_real("save2", "boob1", maintext.feet)
ini_write_real("save2", "boob2", maintext.tempbust)
ini_write_real("save2", "color", maintext.colorblind)
ini_write_real("save2", "1hand", maintext.onehandmode)
savetext = "Selvata's bust size: " + string(ini_read_real("save2", "bust", maintext.bust)) +" inches\nGold: " +string(ini_read_real("save2", "gold", maintext.gold)) +"g";
ini_close();
action1.vampgame = "Save successful!\n\n";
}